### ISSUE TITLE
Subir a RubyGems

### ISSUE THREAD

**Issue by MatayoshiMariano** [TodoPago/SDK-Ruby#1]
@damianwajser porque no subes la gema a http://rubygems.org/?

**Comment by damianwajser** [comment]
Estamos en proceso de definir este esquema, prontamente va a estar allí.
Muchas Gracias!

**Comment by MatayoshiMariano** [comment]
Ok barbaro, si necesitas una mano para subirla avisame.

Saludos.

**Comment by etagwerker** [comment]
@damianwajser Hay algún avance con esto? 

Haría mucho más fácil la instalación de la librería y el seguimiento de las versiones/releases del código.

**Comment by damianwajser** [comment]
Es política de Todo Pago.
A penas me den el ok lo subiremos.
Slds.

**Comment by tommyalvarez** [comment]
@damianwajser Hubo alguna novedad con éste tema?

**Comment by damianwajser** [comment]
La verdad que no.
Podrías comunicarte con soporte técnico de todo pago y solicitarlo.
Disculpa las molestias.
Slds.
