### ISSUE TITLE
Version seteada de savon en el gemspec

### ISSUE THREAD

**Issue by jvalentino90** [TodoPago/SDK-Ruby#5]
Hay alguna razon por la cual setearon la version de savon igual a 2.8.1?
O se podria cambiar para que dependa de savon igual o mayor a 2.8.1?
Gracias!

**Comment by drarko** [comment]
Estimado,

Es por compatibilidad con Ruby 1.9
Si su versión es mayor, puede cambiarlo sin problemas

Saludos

2016-11-08 17:49 GMT-03:00 Juan Valentino <notifications@github.com>:

**Comment by jvalentino90** [comment]
gracias por la pronta respuesta!! 

saludos!

**Comment by drarko** [comment]
Hola TodoPago/SDK-Ruby,
Tienes un mensaje de mauricioghiorzi91 en IQ Elite para ti. 
Haz click aqui a.iqelite.com/j/0NJf2L/yi6/?hg=bNmZ27QFeE para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz click en este enlace: a.iqelite.com/common/unsubscribe/?code=127c874f&email=reply@reply.github.com.&hg=bNmZ27QFeE IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------

**Comment by drarko** [comment]
Hola TodoPago/SDK-Ruby,


Tienes un mensaje de mauricioghiorzi91 en IQ Elite para ti. 


Haz click aqui a.iqelite.com/j/0NJf2L/yi6/?hg=vxChme6lNy para leer el mensaje 


El equipo de IQ Elite



---------------------------------------------------------------------------
Este mensaje estaba destinado a reply@reply.github.com. Si no deseas seguir recibiendo mensajes de IQ Elite, haz click en este enlace: a.iqelite.com/common/unsubscribe/?code=127c874f&email=reply@reply.github.com.&hg=vxChme6lNy IQ Elite es un servicio con oficina principal en: C/ Gran de Gràcia 15, 2º 1ª, 08012 Barcelona, España.
---------------------------------------------------------------------------
