### ISSUE TITLE
Modo test devuelve ERROR: Internal Error

### ISSUE THREAD

**Issue by aserena** [TodoPago/SDK-Ruby#7]
En producción funciona todo bien, pero cuando llamo a sendAuthorizeRequest con el MerchantID y APIKey de test provistos por Todopago me devuelve:

status_code: 999
status_message: 'ERROR: Internal Error'

**Comment by drarko** [comment]
El ambiente Developers esta temporalmente fuera de servicio.
En las proximas horas se estaria solucionando
Saludos
